### ISSUE TITLE
How to send message to player on other proxy ?

### ISSUE THREAD

**Issue by Elikill58** [ProxioDev/RedisBungee#22]
I want to make people communicate between proxies. I just want to send message between proxies.

I through it had something like `api.getProxiedPlayer(UUID)` that return Bungeecord's ProxiedPlayer object, which is implemented to send message to other proxy, and then send it to player. But it doesn't exist.

How can I do ? Does it exist ? Should I made my own messaging system with RedisBungee with commands ?

**Comment by ham1255** [comment]
That will only work if player is on that proxy where code was executed
 
At moment there is no api functionality for this, what you can do instead is get jedis instance and make class that extends jedispubsub

**Comment by ham1255** [comment]
Also to get jedis instance use JedisPool provided by the api 

![image](https://user-images.githubusercontent.com/34905970/142728312-c79ad637-555d-4c7d-b8a1-a1952e723803.jpeg)

**Comment by Elikill58** [comment]
Do you have example ? Such as another message which use this system, or plugin that do it ? Because I don't understand how it will works to get back informations. I have to use JSON or something like that ?

**Comment by ham1255** [comment]
Here is plugin bukkit one thats implments this idea 
https://git.limework.net/Limework/RediSkript

At this class, btw you can avoid the encryption parts 
https://git.limework.net/Limework/RediSkript/src/branch/master/RediSkript-bukkit/src/main/java/net/limework/rediskript/managers/RedisController.java

*Btw it was moved out from github due Govindas which owns the project Due privacy issues*

**Comment by ham1255** [comment]
You dont need all those parts since most of class is skript stuff
You only need runnable interface and jedispubsub

**Comment by Elikill58** [comment]
Sorry for late, but I successed to do what you said, so I close the issue.
