### ISSUE TITLE
How do i sync multiple bungee player counts

### ISSUE THREAD

**Issue by TypicalShavonne** [ProxioDev/RedisBungee#25]
## What is your question?
How do i sync multiple bungee player counts, i have installed redis bungee on all bungeecord setups.

**Comment by ham1255** [comment]
sorry for late response but redisbungee does that automatically in motd

**Comment by TypicalShavonne** [comment]
already fixed lmaoo

**Comment by ham1255** [comment]
> already fixed lmaoo

how is it fix while its question? nani

**Comment by TypicalShavonne** [comment]
sorry, we figured it out already, it was one of our server list plugin that overdriven RedisBungee player count, it was AdvancedNMotd iirc

**Comment by ItsLuiSal07** [comment]
Hello, I have the same problem, how can I solve it?

**Comment by ItsLuiSal07** [comment]
Hello, I have the same problem, how can I solve it?

**Comment by ItsLuiSal07** [comment]
but they simply installed that plugin in all the proxies and the count was already ok?

**Comment by TypicalShavonne** [comment]
try to remove any motd plugin installed

**Comment by TypicalShavonne** [comment]
yes

**Comment by ItsLuiSal07** [comment]
how do you do the motd then? use nullcordX for proxy

**Comment by ham1255** [comment]
this actually problem people keep sending dms to me to fix, but this problem with motd plugin you are using because it overrides what redisbungee sets

**Comment by ItsLuiSal07** [comment]
Which one are you currently using?

**Comment by ham1255** [comment]
> Which one are you currently using? which supports redisBungee? I've been looking and nothing

i don't know any plugins, since mostly these stuff i do myself.

**Comment by ItsLuiSal07** [comment]
podriamos hablar por dc y me haces un complemento de motd que permita Redis?
