### ISSUE TITLE
Backward compatability

### ISSUE THREAD

**Issue by Simonsator** [ProxioDev/RedisBungee#28]
Not anymore relocating the Jedis to com.imaginarycode.minecraft.redisbungee.internal.jedis breaks all plugins using the Jedis from Redis.

**Comment by ham1255** [comment]
Hmmm in that case i should revert it, but problem is if plugin would import redisbungee it will use normal jedis packages naming which also causes error

**Comment by Simonsator** [comment]
If it is importing the compiled version of redisbungee using maven it does use the correct package. And I am not aware of any importing solution where it would use the wrong package.

**Comment by ham1255** [comment]
Current problem it maven project does not know that redisbungee has relocated classes if imported from repository, it kept throwing NoSuchMethod till i removed the relocation, since i mentioned that in the release notes

**Comment by ham1255** [comment]
I might stop shading Jedis and use bungeecord automatic lib loading that was introduced in 1.16

**Comment by Simonsator** [comment]
I am importing it using 

> 		<dependency>
			<groupId>com.github.limework</groupId>
			<artifactId>redisbungee</artifactId>
			<version>0.6.5</version>
			<scope>provided</scope>
		</dependency>
And it works just fine using com.imaginarycode.minecraft.redisbungee as the package for it.

**Comment by ham1255** [comment]
releasing an update shortly
