### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by Simonsator** [ProxioDev/RedisBungee#29]
The project does currently not compile if you have not build the plugin on a previous version on the same machine. That is also the reason why the JitPack deployment failed for 0.7.1. 

One error is that not in all pom.xml the version was changed from 0.7.0 to 0.7.1. But even after changing that it still does not compile so there seem to be more problems with the plugin.

**Comment by ham1255** [comment]
fixed in release 0.7.2
if you are using jitpack import it with this
```
<dependency>
	    <groupId>com.github.limework.redisbungee</groupId>
	    <artifactId>RedisBungee-Bungee</artifactId>
	    <version>0.7.2</version>
</dependency>
```
