### ISSUE TITLE
SENDTOALL COMMAND

### ISSUE THREAD

**Issue by alexeses** [ProxioDev/RedisBungee#32]
## What is your question?
Hello!

I come from an outdated version of RedisBungee and before I could use commands like /sendtoall to send a command to all my proxies. Have you removed the command or is it that it doesn't work directly?

I would like to know if there is any option available.

Thank you very much.

**Comment by ham1255** [comment]
I will be investigating i could have removed some crucial part of the code.

**Comment by alexeses** [comment]
Thank you very much, I look forward to trying any builds you make.

Best regards

**Comment by ham1255** [comment]
This is a mistake i made when i refactored the project, i forgot to include the command class xD, sorry about that, i will be fixing it in next day, for time being use last version 0.6.5 until i publish an update.

**Comment by alexeses** [comment]
Thank you! I will look forward to the update.

**Comment by alexeses** [comment]
Hello! Any word on this error, thank you!

**Comment by Jerimu** [comment]
You did the same for the /plist command im afraid :S

**Comment by ham1255** [comment]
Its whole commands are not registering, but i am currently adding translations related to another issue

**Comment by ham1255** [comment]
fixed
