### ISSUE TITLE
Ability to change redis bungee messages

### ISSUE THREAD

**Issue by alexeses** [ProxioDev/RedisBungee#33]
## What is your question?
Hello!

I've been using RedisBungee for several years and I've always had to have my own fork to modify two messages of the plugin, this has been really annoying because a network in a language other than English looks horrible. 

Could you please implement a setting where we can translate the messages:
- ALREADY_LOGGED_IN 
- ONLINE_MODE_RECONNECT 

I think I and several users who use the plugin would really appreciate it. We can find those messages by [clicking here](https://github.com/ProxioDev/RedisBungee/search?q=contact). 

Thank you very much

**Comment by ham1255** [comment]
ok

**Comment by alexeses** [comment]
Thanks for listening!

**Comment by ham1255** [comment]
#32 not releated by class can be translated

**Comment by Dante5657** [comment]
> currently having issue understanding on how to put multi line text in yaml, i am thinking of using String array which each element is new line or there is good way of doing it.
> 
> any help appreciated

You make it a string list and then call it as getStringList(). format will be following

config-key:
- line1
- line2
- line3
.....

Idk if this was sorted but still
