### ISSUE TITLE
Sendtoall bug

### ISSUE THREAD

**Issue by alexeses** [ProxioDev/RedisBungee#35]
Hello! 

When I use the /sendtoall command it is not sent only once (as it should be), it is sent infinitely until the bungee explodes. is there any way to fix it?

I attach photo;
![image](https://user-images.githubusercontent.com/46347629/176257183-c1f8b65c-845f-4d42-b93c-e56a4558762c.png)
![image](https://user-images.githubusercontent.com/46347629/176257244-c8da1af2-ba8b-4446-8897-5fc80da52fe0.png)

Thank you very much, I am looking forward to it.

**Comment by ham1255** [comment]
Version?

**Comment by alexeses** [comment]
I use the latest version, feel free to try it yourself.

**Comment by ham1255** [comment]
Okay i will investage in few days
Covid hit me hard

**Comment by alexeses** [comment]
Thank you very much, I hope you can get better and it's nothing serious. 

Best regards!

**Comment by ham1255** [comment]
fixed in recent commit
