### ISSUE TITLE
API MOJANG DOWN - KICK ALL PLAYERS 

### ISSUE THREAD

**Issue by alexeses** [ProxioDev/RedisBungee#37]
Hello!

These last few days I have noticed several mojang crashes and my server automatically kicks out all or almost all people. Is it possible that the mojang API is used in some case to check something? 

I feel that when mojang crashes, it kicks out all premium people or similar.

Thank you very much.

**Comment by ham1255** [comment]
Mojang crashed an hour ago, did any kick occur?

**Comment by ham1255** [comment]
Mojang crashed again 2 hours ago? anything?
