### ISSUE TITLE
RedisBungee placeholders do not work for Velocity version

### ISSUE THREAD

**Issue by Dante5657** [ProxioDev/RedisBungee#38]
**Describe the bug**
The Placeholder API Placeholders for RedisBungee does not update on Velocity version

**To Reproduce**

**Expected behavior**
The Placeholders should refresh

**Screenshots**

**Redis version? it should be at least 6 and above.**
6.0.6

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
3.1.1
 

**console logs?**
please provide any errors if there any.

**Comment by Dante5657** [comment]
Turns out the plugin messages are disabled at velocity for now. My bad I guess. If you guys can just tell me if there is a deadline for it to arrive!

**Comment by ham1255** [comment]
no worries,but for some odd reason velocity plugin message is being weird getting random data

**Comment by Dante5657** [comment]
Does it block connections of some sort? If not can I just enable it myself embracing the random data part

**Comment by ham1255** [comment]
> Does it block connections of some sort? If not can I just enable it myself embracing the random data part

no not that,  when the proxy gets the message it gets data that does not make sense like its random, might look at it tomorrow or today.

**Comment by Dante5657** [comment]
> > Does it block connections of some sort? If not can I just enable it myself embracing the random data part
> 
> no not that, when the proxy gets the message it gets data that does not make sense like its random, might look at it tomorrow or today.

Thank you for the fast response. Take your time with the fix

**Comment by areuddin** [comment]
Hi,

Any updates on this?

**Comment by areuddin** [comment]
Hi,

Is there another commit to come or is this the latest commit? It doesn't look like what is required, just wanted to check.

**Comment by ham1255** [comment]
first issue was i was getting random data, now nothing at all....

**Comment by ham1255** [comment]
try building that commit ^ and please tell me your results

**Comment by Dante5657** [comment]
We pushed the latest version on live and the placeholders still show as 0

**Comment by areuddin** [comment]
I can update that it is not working at all, restarting the server or /papi reload will set them to 0 again.

**Comment by ham1255** [comment]
Yup expansion by default refresh rate is 60 seconds

**Comment by ham1255** [comment]
I am reopening this as somebody in spigot messages too reporting getting zeros only

**Comment by ham1255** [comment]
https://github.com/ProxioDev/RedisBungee/commit/482dfc51414d3a73fa18f8c76f415a8b5b04e961
referencing this commit that caused plugin messages to use proxy due fact it was named server

**Comment by ham1255** [comment]
At the moment plugin message from me at least works not sure why it does not for somebody, cause few months ago somebody reported the same issue on bungeecord, before 0.7 internal change, here test i did testing the plugin messages using expansion
with one player on total:
![image](https://user-images.githubusercontent.com/34905970/179428390-67507daf-117c-49f0-8cb8-4dd07714725b.png)
with 2 players:
![image](https://user-images.githubusercontent.com/34905970/179428442-0ab40f9e-fb33-46e2-b2e4-b83db0794fe6.png)
this 2 players on a lobby server:
the command ran 3 times
first one is to tell the expansion to request server on the next request
second was ran `1 second` later would show 0
third time command ran was `1 min` later would show 2 players
![image](https://user-images.githubusercontent.com/34905970/179428497-3c75c5bf-75ed-4281-8156-ad6ecd9d629e.png)

**Comment by areuddin** [comment]
![parse](https://user-images.githubusercontent.com/33463231/179477099-6f63250a-a467-410a-a781-cb390c3d282d.png)
For us the placeholders 'kinda' work, but it's incorrect. At the time of writing this, we have 352 players on, on Lobby 1 it shows 239, so it's showing nearly 100 players less. What doesn't make sense is that we have 3 hub servers, and they all seem to display different %redisbungee_total% counts in the scoreboard.

It's just very mixed, some places still show 0 and they've been up for longer than 60 seconds. I can send the Server IP if you wish so you can see what I mean, let me know.

**Comment by ham1255** [comment]
Hmmm, maybe the expansion is at fault here?

**Comment by ham1255** [comment]
Reason i said that, motd shows correct number of total players, which exclude problem at redisbungee proxy side

**Comment by areuddin** [comment]
Yes, the MOTD is showing the combined player count (we have 2 proxies) - our Minetracker is also showing the correct number

**Comment by Dante5657** [comment]
> > Yes, the MOTD is showing the combined player count (we have 2 proxies) - our Minetracker is also showing the correct number
> 
> Does it have random drops of numbers etc? Like how smooth graphs is.

Its perfectly smooth, Doesnt drop at all

**Comment by Dante5657** [comment]
> > > Yes, the MOTD is showing the combined player count (we have 2 proxies) - our Minetracker is also showing the correct number
> > 
> > Does it have random drops of numbers etc? Like how smooth graphs is.
> 
> Its perfectly smooth, Doesnt drop at all

I feel like the issue is the placeholdersi refresh times because of the refresh time itself or caching. idk exact though

**Comment by ham1255** [comment]
This repository of the expansion by clip, sinxe i update it last year https://github.com/PlaceholderAPI/RedisBungee-Expansion/

**Comment by areuddin** [comment]
> > Yes, the MOTD is showing the combined player count (we have 2 proxies) - our Minetracker is also showing the correct number
> 
> Does it have fluctuations like placeholder one numbers etc? Like how smooth graphs is, also whats interval when getting checked?

https://tracker.gappl.es/

**Comment by ham1255** [comment]
https://github.com/PlaceholderAPI/RedisBungee-Expansion/pull/3
