### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by ConnorServers** [ProxioDev/RedisBungee#44]
Hi.

I have 7 people connected via Main Proxy and 11 people connected via Other Proxy.

When I type `/papi parse me %redisbungee_Prison%`

It only returns 11. - The Other Proxy stats.

How can this be fixed?

Thanks.

**Comment by ConnorServers** [comment]
> 

players were on for a lot longer than 60 seconds so i dont think thats the issue. ):

**Comment by ham1255** [comment]
Paste your redisbungee configuration of the 2 proxies here with removing password.

**Comment by ConnorServers** [comment]
> Paste your redisbungee configuration of the 2 proxies here with removing password.
https://pastebin.com/D2jKgjnm - MAIN PROXY
https://pastebin.com/ptDetkVK - OTHER PROXY

**Comment by ham1255** [comment]
Is yout proxies connecting to same Redis server?

**Comment by ConnorServers** [comment]
> 

Yes

**Comment by ham1255** [comment]
Does your MOTD show right amount of players?

**Comment by ConnorServers** [comment]
> Does your MOTD show right amount of players?

Yes it does on the Main server

**Comment by ham1255** [comment]
What about other one?

**Comment by ConnorServers** [comment]
> What about other one?

the other bungee shows just the players on that server (not total)

**Comment by ham1255** [comment]
Whats your server version?

**Comment by ham1255** [comment]
Also need startup logs of both proxies, only RedisBungee part

**Comment by ConnorServers** [comment]
> Whats your server version?

Prison was on 1.12
Hubs were on 1.17.1

PROXY-OTHER
`[14:40:37] [main/WARN]: INSECURE setup was detected Please setup ssl for your redis instance.
[14:40:37] [main/INFO]: Loaded proxy id Habatsu-MH1.
[14:40:37] [main/INFO]: RedisBungee MODE: SINGLE
[14:40:37] [main/INFO]: Successfully connected to Redis.
[14:40:37] [main/INFO]: 5.0.7 <- redis version
[14:40:37] [main/INFO]: lua manager was loaded
[14:40:37] [main/INFO]: Loaded plugin redisbungee 0.8.0-SNAPSHOT-5c6cf40 by astei, ProxioDev
[14:40:37] [main/INFO]: Loaded 7 plugins`

PROXY-MAIN
`[14:27:16] [main/WARN]: INSECURE setup was detected Please setup ssl for your redis instance.
[14:27:16] [main/INFO]: Loaded proxy id Habatsu-Main.
[14:27:16] [main/INFO]: RedisBungee MODE: SINGLE
[14:27:16] [main/INFO]: Successfully connected to Redis.
[14:27:16] [main/INFO]: 5.0.7 <- redis version
[14:27:16] [main/INFO]: lua manager was loaded
[14:27:16] [main/INFO]: Loaded plugin redisbungee 0.8.0-SNAPSHOT-5c6cf40 by astei, ProxioDev`

**Comment by ConnorServers** [comment]
Any update regarding this?

**Comment by ham1255** [comment]
Nope, cant seem to replicate, but Can you try latest build from github actions, currently unable to use my computer.

Currently looking at your issue its like you are running redis server for each bungee

**Comment by ConnorServers** [comment]
> 

Only 1 redis server for both bungee's.
Yeah I will update and give it a shot

**Comment by ham1255** [comment]
has updating fixed your issue?
