### ISSUE TITLE
1.19.1 Velocity Branch - Does not load

### ISSUE THREAD

**Issue by lukemango** [ProxioDev/RedisBungee#45]
**Describe the bug**
https://pastebin.com/3nYgQ7sJ - plugin does not load

**To Reproduce**
Use https://github.com/PaperMC/Velocity/tree/update/1.19.1 - plugin doesn't load

**Expected behavior**
Plugin to load.

**Screenshots**

**Redis version? it should be at least 6 and above.** Built it from current branch https://github.com/ProxioDev/RedisBungee/commit/fdd537b2760f68ddd61bd43367ead0d3681a10dd

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**  https://github.com/PaperMC/Velocity/commit/c57fb489f3cc664fe05cdbdbb24fdca1347ef446
 

**console logs?**
please provide any errors if there any.
https://pastebin.com/3nYgQ7sJ

**Comment by lukemango** [comment]
nevermind i am a moron

**Comment by ham1255** [comment]
> nevermind i am a moron

you don't have to call your self a moron every time, glad everything worked out.
