### ISSUE TITLE
limboauth support

### ISSUE THREAD

**Issue by licen150** [ProxioDev/RedisBungee#47]
Hi! Can you add limboauth support on velocity? We need to disallow connecting to auth limbo if player has connected to other proxy

**Comment by ham1255** [comment]
This should be done within your plugins as redisbungee api has method to check online players

**Comment by ham1255** [comment]
Limbo auth uses LimboAPI which has event when connecting to a limbo just cancel it in your plugin if player is only using api method i mentioned above
