### ISSUE TITLE
Login event was cancelled but redisbungee see this player as connected

### ISSUE THREAD

**Issue by licen150** [ProxioDev/RedisBungee#48]
**Describe the bug**
I have this bug when i ban player in litebans. When a player tries to connect litebans kicks him and says that he banned but redis shows him as connected and make +1 to server online

**To Reproduce**
1. Install litebans(I think this happens on other plugins too)
2. Ban player
3. Try to connect to server
4. Reds thinks that he is connected

**Screenshots**
![изображение](https://user-images.githubusercontent.com/38755713/189947286-8be0a537-a716-4d64-b2b8-36b4dbdde318.png)

**Redis version? 7.0.4**

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
 Velocity latest build

**console logs?**
[redisbungee]: Player found in set that was not found locally and globally: 1e9f86a8-ab44-31ea-a2e2-a7119377341b

**Comment by ham1255** [comment]
Whats your redisbungee version this was fixed few versions ago

**Comment by licen150** [comment]
Latest build redisbungee 0.8.0

**Comment by ham1255** [comment]
But generally its safe to ignore the warning it just says that player not found and corrects the data in redisbungee

**Comment by ham1255** [comment]
Could you retry banning etc with litebans etc in video with showing the command *glist showall*

**Comment by licen150** [comment]
https://user-images.githubusercontent.com/38755713/189960970-144aec19-ccdb-4b0f-8322-975b2ed966ad.mp4

**Comment by ham1255** [comment]
oops shouldn't close but try latest build in before closing.https://github.com/ProxioDev/RedisBungee/actions/runs/3050087447/jobs/4916812653

**Comment by ham1255** [comment]
Have you tested?

**Comment by licen150** [comment]
._.
![image](https://user-images.githubusercontent.com/38755713/190248889-814439c4-3713-480c-a229-d1cca489b09d.png)

**Comment by ham1255** [comment]
?

**Comment by licen150** [comment]
bug still exists... very strange
