### ISSUE TITLE
RedisBungee lost sync on coutning online people.  

### ISSUE THREAD

**Issue by korallo159** [ProxioDev/RedisBungee#49]
Motd shows wrong players count

Online people chart: 
![image](https://user-images.githubusercontent.com/53827110/193217528-c75586bd-19c2-4957-b1ff-78bbbe2ddcab.png)

Used redis:
latest redis docker image (7)

Used proxy version:
Flamecord latest (1.19)

**Comment by korallo159** [comment]
I have 3 proxy connected.

**Comment by ham1255** [comment]
How did you setup your redis server? since i see like each proxy from graphs that they are isolated

**Comment by korallo159** [comment]
I am using docker for hosting redis (on separate server)
I mean it works properly, but sometimes this bug happens. 
This is for example chart from today.
![image](https://user-images.githubusercontent.com/53827110/193303112-7696e908-fdca-4916-89c9-5214f7ca9679.png)

example configuration of one proxy:
![image](https://user-images.githubusercontent.com/53827110/193303369-29d8eba2-e0a3-4d38-a549-dea69f004898.png)

**Comment by ham1255** [comment]
Looks from config you are probably using 0.7 or 0.6 Can you try compiling master branch of redisbungee

**Comment by ham1255** [comment]
any update on this? if not closing it, reply to open it back.
