### ISSUE TITLE
RedisVelocity Maven does not exist

### ISSUE THREAD

**Issue by Simonsator** [ProxioDev/RedisBungee#52]
I am using this Maven pom:
```XML
	<repository>
		<id>jitpack.io</id>
		<url>https://jitpack.io</url>
	</repository>
	</repositories>
	<dependencies>
		<dependency>
			<groupId>com.github.limework.redisbungee</groupId>
			<artifactId>RedisBungee-Velocity</artifactId>
			<version>0.8.0-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
```

Maven is unable to find the dependency RedisBungee-Velocity in jitpack.io. It seems like the artifact was not uploaded to Jitpack.io or under the wrong name.

**Comment by ham1255** [comment]
It should be uploaded as logs confirm it

**Comment by ham1255** [comment]
`[INFO] RedisBungee-Velocity ............................... FAILURE [ 16.033 s]`
found that in jitpack log

**Comment by ham1255** [comment]
try this now:
```
<dependency>
	    <groupId>com.github.limework.redisbungee</groupId>
	    <artifactId>RedisBungee</artifactId>
	    <version>0.8.0-FixJitPack</version>
	     <scope>provided</scope>
</dependency>

**Comment by ham1255** [comment]
https://github.com/ProxioDev/RedisBungee/commit/21f543581ca81b6ea5154c41b1df7dcb784f4b60
