### ISSUE TITLE
Redisbungee displaying wrong playercounts

### ISSUE THREAD

**Issue by Skydinse-de** [ProxioDev/RedisBungee#54]
Hi, I've noticed, that Redisbungee starts to display wrong playercounts after a certain amount of time. And this wrong playercount
won't change at all until i reboot my Waterfall (Bungeecord fork) server.

I've already read the FAQ and i can say that:

 - My configuration should be correct.
 - The Redis server is running. It currently has no password for testing purpuses but i don't think it causes the error.
 - All my Bungeecords are running.
 - The Time in all my Bungeecord machines should be alright as they currently are all on the same machine.
 - Every Bungeecord has the same version of Redisbungee.
 - I'm running the latest version of Redisbungee

There are no logs

I've attached my Config (I changed the IP adress in this example for some obvious reasons).
I always use the IPV4 adress of my Redis server

It's named "config.txt". Don't worry I named it config.yml on the Bungeecord

Sorry for my bad english if any of this grammar dosen't makes sence ;)

[config.txt](https://github.com/ProxioDev/RedisBungee/files/10079257/config.txt)

**Comment by ham1255** [comment]
I seen people sending me dms about this i am not sure what is going wrong.

**Comment by ham1255** [comment]
Do you have any screenshots?

**Comment by ham1255** [comment]
RedisBungee has integrity check task which handle incase of desync happens.

**Comment by Skydinse-de** [comment]
> Do you have any screenshots?

![image](https://user-images.githubusercontent.com/118938495/203793629-f021868d-a51a-402e-9202-f335db5042d5.png)
It's a german server

**Comment by ham1255** [comment]
Just to make sure, is all redisbungees uses same redis instance?

**Comment by Skydinse-de** [comment]
Just made sure. They do. When I restart the weird proxy everything works until in a few hours a proxy (can be the same or a different one) decides to bug out.

What's interesting is that even if a proxy does not know the propper playercont it can display all online players with /glist showall
![image](https://user-images.githubusercontent.com/118938495/203826684-a7935630-1133-4aa1-a728-3f013e08cfa4.png)

Is it possible that Multipaper or Playerbalancer can be the reason. I've already turned "redisbungee" on in playerbalancer though

**Comment by ham1255** [comment]
So glist displays right stuff... hmmm i might need to lookup the motd code

**Comment by ham1255** [comment]
MultiPaper cant cause these problems as redisbungee is proxy plugin

**Comment by ham1255** [comment]
could you try this

can you set password to your redis instance?

**Comment by Skydinse-de** [comment]
I'll try

**Comment by ham1255** [comment]
Any updates?

**Comment by Skydinse-de** [comment]
I've been running it for a few days now. Since then it never did happen again. Thanks! I'll keep you informed if anything odd happens.

**Comment by ham1255** [comment]
> I've been running it for a few days now. Since then it never did happen again. Thanks! I'll keep you informed if anything odd happens.

Thanks for letting me know everything solved will be closing the issue now,
But whats weird to me that people did actually run problem with redisbungee but with other strange issues, and the fix was setting the password, is it me or there is weird pattern going on here? *like redis itself is misbehaving with no password i set*
