### ISSUE TITLE
Update okhttp / switch to okhttp3

### ISSUE THREAD

**Issue by andreasdc** [ProxioDev/RedisBungee#56]
Okhttp seems to be updated, can you update it to the latest version?

**Comment by ham1255** [comment]
Whats wrong with current version?

**Comment by andreasdc** [comment]
Shouldn't newer version be better?

**Comment by ham1255** [comment]
it appears that newer versions are written in kotlin so i made separate for now

**Comment by ham1255** [comment]
i Have decided that to keep OkHttp client on version 2 as version 3 and above includes kotlin libs that we dont even need.
