### ISSUE TITLE
Config and messages are taken from bungeecord

### ISSUE THREAD

**Issue by andreasdc** [ProxioDev/RedisBungee#60]
After installing the plugin config.yml and messages.yml are from the bungeecord.

**Comment by linsaftw** [comment]
Probably because you are using BungeeCord and probably RedisBungee uses BungeeCord Configuration or Messages Configuration instead of the normal Configuration system provided for plugins.

**Comment by ham1255** [comment]
so whats the problem again?

**Comment by andreasdc** [comment]
After installing the plugin defaults of config.yml and messages.yml are not from the plugin, but from the bungeecord.

**Comment by ham1255** [comment]
it doesn't make sense, Plugin when starts up it adds default config if it does not detect them, or config version is old

unless i am not understanding anything could you elaborate more?

**Comment by andreasdc** [comment]
Default config contains bungeecord's config, not plugin's config.

**Comment by ham1255** [comment]
i have you checked the plugin's folder?

> Default config contains bungeecord's config, not plugin's config.

**Comment by andreasdc** [comment]
Yea, it contains config.yml, messages.yml and old_config folder. config and messages are from bungeecord files.

**Comment by ham1255** [comment]
> Yea, it contains config.yml, messages.yml and old_config folder. config and messages are from bungeecord files.

send screenshot please

**Comment by andreasdc** [comment]
what do you want to see

**Comment by ham1255** [comment]
.ymls files content and remove any sensitive data like passwords etc

**Comment by andreasdc** [comment]
config.yml of redisbungee contains config.yml of bungeecord
messages.yml of redisbungee contains messages.yml of bungeecord

**Comment by ham1255** [comment]
alright then.... what kind of hosting company you are using?

**Comment by andreasdc** [comment]
no, they dont replace the files

**Comment by ham1255** [comment]
can you send server startup logs, i need to check whats going on.

**Comment by andreasdc** [comment]
i didn't see anything unnormal there

**Comment by ham1255** [comment]
even if you see nothing abnormal i need these stuff
* bungeecord config file
* bungeecord messages file
* RedisBungee messages file
* RedisBungee config file
* server logs even if there is no abnormal stuff

**Comment by andreasdc** [comment]
maybe it's because bungeecord jar is in another folder, idk and i don't want to check more

**Comment by linsaftw** [comment]
If you are not collaborating with the developer it means your lack of interest with the issue and will not get solved.

**Comment by andreasdc** [comment]
Sure, but I don't really have interest and strenght to explain this issue more.
