### ISSUE TITLE
Connecting players to other proxy in event of proxy crash/shutdown

### ISSUE THREAD

**Issue by Coquettishpig** [ProxioDev/RedisBungee#63]
I want to make it so that when an agent is shut down, the players on that agent are assigned to other agents, how should I do this and do I need to use redis-cluster-servers?

**Comment by ham1255** [comment]
what is the `agent`?

**Comment by Coquettishpig** [comment]
> I want to make it so that when an agent is shut down, the players on that agent are assigned to other agents

I want to make it so that when an bungee is shut down, the players on that bungeeare assigned to other bungee

**Comment by Coquettishpig** [comment]
Do I need to turn on cluster-mode-enabled if I want to do this？

**Comment by ham1255** [comment]
if you mean proxy, no you can't transfer players on proxy crash/shutdown, due minecraft java edition not having something  called transfer packet

this possible on bedrock edition of the game, due existence of transfer packet

read the readme file https://github.com/ProxioDev/RedisBungee#notes for more information

**Comment by Coquettishpig** [comment]
> 如果您的意思是代理，不，您无法在代理崩溃/关闭时转移玩家，因为 Minecraft Java 版没有称为传输数据包的东西
> 
> 这可能在游戏的基岩版上，由于存在传输数据包
> 
> 有关详细信息，请阅读自述文件 https://github.com/ProxioDev/RedisBungee#notes

Thank you very much for my answer, I know

**Comment by kit8379** [comment]
[23:05:14 WARN] [redisbungee]: Player found in set that was not found locally and globally: 200655d2-32a1-4176-8b06-445cd59b4874

I get stucked and can't connect to server because of this. Can you add an option to force the exist player log out to the server?

**Comment by slash1div** [comment]
Transfer packets were added in 24w03a. It should be released in 1.20.5. I can't wait to see this implemented in plugins.

**Comment by ham1255** [comment]
> Transfer packets were added in 24w03a. It should be released in 1.20.5. I can't wait to see this implemented in plugins.

Yes i have updated readme on development branch for this, but we have to see how proxies will implement the api
