### ISSUE TITLE
Maybe make it run on Spigot

### ISSUE THREAD

**Issue by BingYanchi** [ProxioDev/RedisBungee#65]
## What is your question?
It may be possible to add functionality to run on Spiogt, not provide any functionality, and provide an API for developers to pass information on Proxy and Spigot.
Unlike the traditional Bukkit Message Channel, Redis can communicate without players.
For example, it can provide information exchange for a server matching system running multiple areas on a single server. I think it's a very interesting thing.

**Comment by ham1255** [comment]
This plugin is intended for Proxies only, but since you mentioned you want to sync the data using redis.

RedisBungee uses Jedis library internally, which can achieve what you want.

https://github.com/redis/jedis
