### ISSUE TITLE
USername?

### ISSUE THREAD

**Issue by FuchsFuchs1** [ProxioDev/RedisBungee#68]
So i have ACL setup on redis and there no username value in config...

**Comment by ham1255** [comment]
can you test if this does work? https://github.com/ProxioDev/RedisBungee/tree/redisusername

**Comment by FuchsFuchs1** [comment]
can you send me a jar for bungeecord?

**Comment by ham1255** [comment]
currently github action is building it will post a link

**Comment by ham1255** [comment]
https://github.com/ProxioDev/RedisBungee/actions/runs/4681100507

**Comment by FuchsFuchs1** [comment]
yay it works
Thanks alot!!! 

(also sorry for late responce)
