### ISSUE TITLE
Documentation issue: plugin message channel is incorrect

### ISSUE THREAD

**Issue by Espiiii-debug** [ProxioDev/RedisBungee#81]
Hello, there seems to be an error with your documentation regarding the channel name. You noted "RedisBungee" out the correct channel is: "legacy:redisbungee".
Also, your maven repo is not working.
We also find conflicts when reading your documentation regarding the maven dependency to use. Sometimes we have RedisBungee, other times RedisBungee-Bungee for artifacts. And id groups also vary.

**Comment by ham1255** [comment]
Wiki of this project is really old, 
Plus on how to use it in a plugin is written in the  readme of the project

**Comment by ham1255** [comment]
fixed
