### ISSUE TITLE
Commands doesn't work

### ISSUE THREAD

**Issue by shaqupl** [ProxioDev/RedisBungee#90]
**Every redisbungee comand from your wiki doesn't work**
![image](https://github.com/ProxioDev/RedisBungee/assets/68109218/31a6e218-cc73-4435-9580-791481e9ee75)

**To Reproduce**
1. execute /plist
2. command not fount

**Expected behavior**
plist should print players connected to different proxies.

**Redis version? it should be at least 6 and above.**
0.11.3
**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
 aegis 1.20.1 fork of waterfall and anitbot bungee

**Comment by ham1255** [comment]
Check redis bungee config where it says legacy commands as by default its set to false

**Comment by ham1255** [comment]
Also do not use the wiki its super old
