### ISSUE TITLE
Freezing BungeeCord

### ISSUE THREAD

**Issue by yooniks** [ProxioDev/RedisBungee#91]
**Describe the bug**
RedisBungee freezes my server every night. 4 proxies with total of about 1600 players.
I have default RedisBungee config.

When redisBungee freezes one of my proxies then it doesn't kick players from the servers but it doesn't let them join to the freezed proxy and /glist and /rplist seems to be freezed too, nothing happens when you execute these commands and it stops to send information about player's count to other proxies.

**To Reproduce**
Get 4 bungee proxies, 1600 players and wait a few days and then proxies randomly get freezed every day.

**Expected behavior**
Not freezing my proxies

**Redis version? it should be at least 6 and above.**
 Redis version=6.0.16

**Bungeecord version or (the bungee fork name eg: waterfall) and your plugins**
 1.20.1 BungeeCord, the same problem happened to me with the latest velocity (i thought it will solve the problem, but it didn't)

**console logs?**
there are 100% no errors.

**Comment by ham1255** [comment]
hello, sorry for late response, could you provide a thread dump when it happens?

**Comment by yooniks** [comment]
> also other question, does whole command execution stop in proxy too? for example command end in the proxy
No, only redisbungee commands stop working. /rplist, /glist and it's stops synchrozining player count on that proxy that is freezed. Every other command like /end or /server works fine.

I have spark heapdump if you want, but it's 620mb so maybe i send it to you privately somewhere?

**Comment by ham1255** [comment]
> > also other question, does whole command execution stop in proxy too? for example command end in the proxy
> 
> No, only redisbungee commands stop working. /rplist, /glist and it's stops synchrozining player count on that proxy that is freezed. Every other command like /end or /server works fine.
> 
> I have spark heapdump if you want, but it's 620mb so maybe i send it to you privately somewhere?

i need thread dump as well try sending it to me on discord its same user as github

**Comment by ham1255** [comment]
Being tracked on #91
