### ISSUE TITLE
[Feature Request] Option to choose which commands are overriden

### ISSUE THREAD

**Issue by ReclinesMC** [ProxioDev/RedisBungee#93]
Certain commands I have are custom, but others I would prefer to be overriden. It would be nice if we could choose :)

**Comment by ham1255** [comment]
Planned for 0.12.0

**Comment by ReclinesMC** [comment]
I saw you tagged this on bungee, will this also be for velocity too?

**Comment by ham1255** [comment]
Oops was a mistake sorry about that
