### ISSUE TITLE
Keep getting this error. Anyone know why?

### ISSUE THREAD

**Issue by ArcheryAce** [ProxioDev/RedisBungee#95]
## What is your question?
Hey, I keep getting this error in my Supposed Proxy network server. Could someone tell me what It means and what I can do to fix the issue?
There are no issues regarding players on the server. just getting that error sent every time a player joins.
![image](https://github.com/ProxioDev/RedisBungee/assets/74921968/0c9f9c0c-06e6-4be9-96da-ef45895a18d2)

**Comment by ham1255** [comment]
Weird... issue templates didnt get applied anyways.

I need more information like RedisBungee version and whats velocity version please provide full logs as text not a picture

**Comment by ham1255** [comment]
This error is super weird I am not sure how Player is being casted into a hashmap

**Comment by ArcheryAce** [comment]
> This error is super weird I am not sure how Player is being casted into a hashmap ValuesView

I am not sure either. that is why I came here to ask you since It just started showing up recently. Do you know what a fix would be?

**Comment by ham1255** [comment]
can you try updating velocity version that you are using? its from Feb 24

**Comment by ArcheryAce** [comment]
> can you try updating velocity version that you are using? its from Feb 24

I can ask my server owner if we can do that.

**Comment by ham1255** [comment]
any issues?
